name: example
description: A new Flutter project.

publish_to: 'pub.dev'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive_listener:
    path: ../
  hive: ^2.0.4
  hive_flutter: ^1.0.0